src/WebPomodoro/Models/Activity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebPomodoro.Models
{
    public class Activity
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Place { get; set; }
        public int Type { get; set; }  // Unplanned Urgent 
        public int Interrupted { get; set; }
        public int Abandoned { get; set; }
        public int Completed { get; set; }
        public DateTime ActivityDate { get; set; }
        public DateTime DueDate { get; set; }
        public bool IsDone { get; set; }
    }

}

src/WebPomodoro/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using WebPomodoro.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WebPomodoro.Controllers
{
    public class ActivityController : Controller
    {
        private ApplicationDbContext db;

        public ActivityController(ApplicationDbContext context)
        {
            db = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var activities = from a in db.Activity
                             select a;
            
            return View(activities);
        }

        // GET: /<controller>/Edit
        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Edit Activity";
            var activity = (from a in db.Activity
                           where a.ID == id
                           select a).SingleOrDefault();

            if (activity == null)
            {
                ViewData["Title"] = "Add Activity";
                activity = new Activity()
                {
                    Description = "New",
                    ActivityDate = DateTime.Now,
                    Place = "Work"
                };
            }

            return PartialView(activity);
        }

        public IActionResult StartTimer(int id)
        {
            ViewData["title"] = "Start Timer";
            var activity = (from a in db.Activity
                            where a.ID == id
                            select a).SingleOrDefault();

            return PartialView(activity);
        }

        [HttpPost]
        public IActionResult Edit(Activity activity)
        {
            if (ModelState.IsValid)
            {
                var act = (from a in db.Activity
                           where a.ID == activity.ID
                           select a).SingleOrDefault();

                if (act != null)
                {
                    act.Description = activity.Description;
                    act.ActivityDate = activity.ActivityDate;
                    act.Place = activity.Place;

                    db.Entry(act).Property(p => p.Description).IsModified = true;
                    db.Entry(act).Property(p => p.ActivityDate).IsModified = true;
                    db.Entry(act).Property(p => p.Place).IsModified = true;
                }
                else
                {
                    act = new Activity()
                    {
                        Description = activity.Description,
                        ActivityDate = activity.ActivityDate,
                        Place = activity.Place
                    };
                    db.Add(act);
                }

                db.SaveChanges();

                return Json(new { result = "valid" });
            }
            else
            {
                return PartialView(activity);
            }
        }


        public IActionResult Delete(int id)
        {
            var activity = (from a in db.Activity
                            where a.ID == id
                            select a).SingleOrDefault();

            return PartialView(activity);
        }

        [HttpPost]
        public IActionResult Delete(Activity activity)
        {
            var act = (from a in db.Activity
                            where a.ID == activity.ID
                            select a).SingleOrDefault();

            if (act != null)
            {
                db.Remove(act);
                db.SaveChanges();

                return Json(new { result = "valid" });
            }
            else
            {
                return PartialView(activity);
            }
        }

        public JsonResult tasks()
        {
            return Json(new {
                task1 = new { isDone = false, description = "First Task" },
                task2 = new { isDone = true, description = "Second Task" },
                task3 = new { isDone = false, description = "Third Task" },
            });
        }
    }
}

src/WebPomodoro/Views/Activity/Delete.cshtml
@model Activity

@{
    ViewData["Title"] = "Delete Activity";
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Deletet Activity</h4>
        </div>
        <div class="modal-body">
            <form id="frmEdit" class="form-horizontal">
                <input type="hidden" asp-for="ID" />
                <div>Are you sure you want to delete <strong>@Model.Description</strong>?</div>
            </form>
            <div class="clearfix"></div>
        </div>
        <div class="modal-footer">
            <button id="btnOk" type="button" class="btn btn-primary">OK</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
    </div>
</div>

<script>
    $("#btnOk").on("click", function () {
        $.ajax({
            url: '@Url.Action("Delete", "Activity")',
            data: $("#frmEdit").serialize(),
            type: "POST",
            success: function (data) {
                if (data.result == "valid") {
                    $("#dialog").modal("hide");
                    location.reload();
                } else {
                    $("#dialog").html(data);
                }
            }
        });
    });
</script>

src/WebPomodoro/Views/Activity/Edit.cshtml
@model Activity

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">@ViewData["Title"]</h4>
        </div>
        <div class="modal-body">
            <for id="frmEdit" class="form-horizontal">
                <input type="hidden" asp-for="ID" />
                <div asp-validation-summary="ValidationSummary.ModelOnly" class="danger"></div>
                <div class="form-group">
                    <label asp-for="Description" class="col-sm-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="ActivityDate" class="col-sm-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="ActivityDate" class="form-control" type="datetime" />
                        <span asp-validation-for="ActivityDate" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Place" class="col-sm-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Place" class="form-control" />
                        <span asp-validation-for="Place" class="text-danger" />
                    </div>
                </div>
            </for>
            <div class="clearfix"></div>
        </div>
        <div class="modal-footer">
            <button id="btnUpdate" type="button" class="btn btn-primary">OK</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
    </div>
</div>

<script>
    $("#btnUpdate").on("click", function () {
        $.ajax({
            url: '@Url.Action("Edit", "Activity")',
            data: $("#frmEdit").serialize(),
            type: "POST",
            success: function (data) {
                if (data.result == "valid") {
                    $("#dialog").modal("hide");
                    location.reload();
                } else {
                    $("#dialog").html(data);
                }
            }
        });
    });
</script>

src/WebPomodoro/Views/Activity/Index.cshtml
@model IEnumerable<Activity>

@{
    ViewData["Title"] = "Activity List";
}

<h2>TODO TODAY</h2>
<p>Activity that I need to do today.</p>

<table class="table table-striped table-hover">
    <tr>
        <th>Done</th>
        <th>@Html.DisplayNameFor(model => model.Description)</th>
        <th>@Html.DisplayNameFor(model => model.Place)</th>
        <th>@Html.DisplayNameFor(model => model.ActivityDate)</th>
        <th></th>
    </tr>
    @foreach (var act in Model)
    {
        <tr>
            <td>
                <input type="checkbox" />
            </td>
            <td>
                <a asp-action="StartTimer" asp-route-id="@act.ID" class="starttimer" data-ajax="true" data-toggle="modal" data-target="#dialog">
                    <span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>
                </a>
                <a asp-action="Edit" asp-route-id="@act.ID" class="edit" data-ajax="true" data-toggle="modal" data-target="#dialog">
                    @Html.DisplayFor(modelItem => act.Description)
                </a>
            </td>
            <td>@Html.DisplayFor(modelItem => act.Place)</td>
            <td>@Html.DisplayFor(modelItem => act.ActivityDate)</td>
            <td class="text-center">
                <a asp-action="Delete" asp-route-id="@act.ID" class="delete" data-ajax="true" data-toggle="modal" data-target="#dialog">
                    <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    }
</table>
<button id="btnAdd" class="btn btn-primary" data-toggle="modal" data-target="#dialog" data-ajax="true">
    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add Activity
</button>

<div class="row">&nbsp;</div>

<div class="col-6">
    <table id="tblTasks" class="table table-hover">
        <thead>
            <tr>
                <th>Done</th>
                <th>Task</th>
                <th></th>
            </tr>
        </thead>
        <tbody data-bind="foreach: tasks, visible:tasks().length > 0">
            <tr class="tbl-row">
                <td style="width:50px;">
                    <input type="checkbox" data-bind="checked: isDone" />
                </td>
                <td style="min-width:250px;">
                    <a href="" class="select">
                        <span class="glyphicon glyphicon-play"></span>
                    </a>
                    <a href="" data-bind="text: description, css: {done: isDone()}"></a>
                </td>
                <td>
                    <a href="" class="select">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<button id="btnAddTask" class="btn btn-primary" data-toggle="modal" data-target="#dialog-edit" data-ajax="true">
    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add Activity
</button>
<div class="row">&nbsp;</div>
<ul class="list-group" data-bind="foreach: tasks, visible:tasks().length > 0">
    <li class="list-group-item">
        <span class="badge"></span>
        <input type="checkbox" data-bind="checked: isDone" />
        <a href="" data-bind="text: description, css: {done: isDone()}"></a>
        <div class="row">
            <a href="" class="">
                <span class="glyphicon glyphicon-play"></span>
            </a>
            <a href="" class="">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
        </div>
    </li>
</ul>


@section scripts{
    <script>
        function refreshTable() {
            //triggers update event to refresh the UserList table data
            table.trigger('update');
        }

        $(".edit").click(function () {
            $.ajax({
                url: $(this).prop("href"),
                type: "GET",
                cache: false,
                success: function (data) {
                    $("#dialog").html(data);
                },
                error: function (xhr, state, thrownError) {
                    $("#dialog").html(JSON.stringify(xhr));
                }
            });
        });

        $(".delete").click(function () {
            $.ajax({
                url: $(this).prop("href"),
                type: "GET",
                cache: false,
                success: function (data) {
                    $("#dialog").html(data);
                },
                error: function (xhr, state, thrownError) {
                    $("#dialog").html(JSON.stringify(xhr));
                }
            });
        });


        $("#btnAdd").click(function () {
            $.ajax({
                url: '@Url.Action("Edit", "Activity", new {id=-1})',
                type: "GET",
                cache: false,
                success: function (data) {
                    $("#dialog").html(data);
                },
                error: function (xhr, state, thrownError) {
                    $("#dialog").html(JSON.stringify(xhr));
                }
            });
        });

        $(".starttimer").click(function () {
            $.ajax({
                url: $(this).prop("href"),
                type: "GET",
                cache: false,
                success: function (data) {
                    $("#dialog").html(data);
                },
                error: function (xhr, state, thrownError) {
                    $("#dialog").html(JSON.stringify(xhr));
                }
            });
        });

        function Task(data) {
            this.isDone = ko.observable(data.isDone);
            this.description = ko.observable(data.description);
        }

        function TaskListViewModel() {
            var self = this;
            self.tasks = ko.observableArray([]);
            self.newTaskText = ko.observable();
            self.incompleteTasks = ko.computed(function () {
                return ko.utils.arrayFilter(self.tasks(), function (task) { return !task.isDone() });
            });

            // Operations
            self.addTask = function () {
                self.tasks.push(new Task({ description: this.newTaskText() }));
                self.newTaskText("");
            };
            self.removeTask = function (task) { self.tasks.remove(task) };

            // Load initial state from server, convert it to Task instances, then populate self.tasks
            $.getJSON("/activity/tasks", function (allData) {
                var mappedTasks = $.map(allData, function (item) { return new Task(item) });
                self.tasks(mappedTasks);
            });
        }

        $(function () {
            //document is ready.
            ko.applyBindings(new TaskListViewModel());
        });
    </script>
}

src/WebPomodoro/Views/Activity/StartTimer.cshtml
@model Activity

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">@ViewData["Title"]</h4>
        </div>
        <div class="modal-body">
            <input type="hidden" asp-for="ID" />
            <form id="frmTimer" class="form-horizontal">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>Activity: </strong>@Model.Description
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-8">
                                <canvas id="myCanvas" width=200 height=200></canvas>
                            </div>
                            <div class="col-sm-4">
                                <p>
                                    <a id="btnInterrupt" class="btn btn-success">Interruption</a>
                                </p>
                                <p>
                                    <a id="btnAbandon" class="btn btn-danger">Abandoned</a>
                                </p>    
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="clearfix"></div>
        </div>
        <div class="modal-footer">
            <button id="btnOk" type="button" class="btn btn-primary">OK</button>
            <button id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
    </div>
</div>


<script>
    function Done() {
        //console.log("I am Done!");
        alert("Time is up!");
    }

    var countDown = new CountDown(document.getElementById("myCanvas"), 25, Done);
    countDown.Start();
    
    $("btnInterrupt").click(function () {
        alert("Interrupted!");
        //Add code to handle an interruption.
    });

    $("btnAbandon").click(function () {
        alert("Abandon Pomodoro!");
        //Add code to handle abandon pomodoro.
    });

    $("#btnOk").click(function () {
        countDown.Stop();
        $("#dialog").modal("hide");
        location.reload();
    });

    $("#btnCancel").click(function () {
        countDown.Stop();
        $("#dialog").modal("hide");
    });

</script>